#!/bin/bash

if [ -f /opt/custom_run ]; then
    chmod u+x /opt/custom_run
    echo "=>executing /opt/custom_run"
    /opt/custom_run
fi

/opt/setup/icinga2

service icinga2 start

trap "service icinga2 stop" HUP INT QUIT ABRT KILL ALRM TERM TSTP

tail -f /var/log/icinga2/icinga2.log &

while pidof icinga2 &>/dev/null; do sleep 5; done
