#!/bin/bash

/opt/setup/icinga2_proposed_by_director

service icinga2 start

trap "service icinga2 stop" HUP INT QUIT ABRT KILL ALRM TERM TSTP

tail -f /var/log/icinga2/icinga2.log &

while pidof icinga2 &>/dev/null; do sleep 5; done
