#!/bin/bash

source /etc/profile.d/rvm.sh \
    && rvm install 2.4.1 \
    && rvm --default use 2.4.1

gem install --no-ri --no-rdoc nagios-plugin
gem install --no-ri --no-rdoc sidekiq
rvm current

/opt/setup/icinga2_proposed_by_director

service icinga2 start

trap "service icinga2 stop" HUP INT QUIT ABRT KILL ALRM TERM TSTP

tail -f /var/log/icinga2/icinga2.log &

while pidof icinga2 &>/dev/null; do sleep 5; done
